# Generated by Django 5.1.1 on 2024-09-22 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="contentTwo",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="ingredients",
        ),
    ]
